# Need 3.3v USB to UART/TTL adapter for initial flashing
# https://docs.m5stack.com/en/unit/poesp32
# poesp32 - usb uart
# GND  <--> GND
# G0   <--- GND (or DTR)
# EN   <--- N/A (or DSR)
# RX   <--- TX
# TX   ---> RX
# 3V3  <--- 3v3

substitutions:
  name: m5stack-poesp32
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
  
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

api:
logger:
ota:

  dashboard_import:
    package_import_url: github://notsonominal/public/m5stack-poesp32-nomac.yaml@main
    import_full_config: true

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

